name: Build with Maven

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Restore Maven cache
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        run: mvn -B clean package --file pom.xml
      - name: Archive artifact
        uses: actions/upload-artifact@v2.2.0
        with:
          name: "gCV-Bridge"
          path: "target/gCV-Bridge-*.jar"
          if-no-files-found: error
